### ISSUE TITLE
The text color is not the same color

### ISSUE THREAD

**Issue by mystiquewolf** [aunetx/smart-transparent-top-bar#2]
Take a look at the top.
![2020-05-19_20-59](https://user-images.githubusercontent.com/16529989/82363114-10cc3d80-9a16-11ea-80d9-2cb8a56a90ed.png)

**Comment by mystiquewolf** [comment]
Forgot to mention that this is when i select a custom #000000 color, when applications are not touching the bar. It's not by default that way. ;)

**Comment by aunetx** [comment]
Thanks a lot for filling the issue !

I think that I understand why it does not change well the color, as my method is a bit of a hack... What extensions are you using? I will try with them installed ^^

**Comment by mystiquewolf** [comment]
Oh, that's a long list (both positive and negative of Gnome).

- [Autohide battery](https://extensions.gnome.org/extension/595/autohide-battery/)
- [Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/)
- [Control Blur Effect On Lock Screen](https://extensions.gnome.org/extension/2935/control-blur-effect-on-lock-screen/)
- [Coverflow Alt-Tab](https://extensions.gnome.org/extension/97/coverflow-alt-tab/)
- [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/)
- [Desktop Icons](https://extensions.gnome.org/extension/1465/desktop-icons/)
- [Dim on battery power](https://extensions.gnome.org/extension/947/dim-on-battery-power/)
- [Disconnect Wifi](https://extensions.gnome.org/extension/904/disconnect-wifi/)
- [Emoji Selector](https://extensions.gnome.org/extension/1162/emoji-selector/)
- [Grown-up notifications](https://extensions.gnome.org/extension/1335/grown-up-notifications/)
- [GSConnect](https://extensions.gnome.org/extension/1319/gsconnect/)
- [Harddisk LED](https://extensions.gnome.org/extension/988/harddisk-led/)
- [Lock Keys](https://extensions.gnome.org/extension/36/lock-keys/)
- [Mpris Indicator Button](https://extensions.gnome.org/extension/1379/mpris-indicator-button/)
- [Notification Counter](https://extensions.gnome.org/extension/1386/notification-counter/)
- [OpenWeather](https://extensions.gnome.org/extension/750/openweather/)
- [Panel scroll](https://extensions.gnome.org/extension/1616/panel-scroll/)
- [Places Status Indicator](https://extensions.gnome.org/extension/8/places-status-indicator/)
- [Pomodoro](https://extensions.gnome.org/extension/53/pomodoro/)
- [Refresh Wifi Connections](https://extensions.gnome.org/extension/905/refresh-wifi-connections/)
- [Remove Accessibility](https://extensions.gnome.org/extension/112/remove-accesibility/)
- [ShutdownTimer](https://extensions.gnome.org/extension/792/shutdowntimer/)
- [Smart transparent topbar](https://extensions.gnome.org/extension/2588/fully-transparent-top-bar/)
- [User Themes](https://extensions.gnome.org/extension/19/user-themes/) to be able to change light and dark shell theme from Tweaks

P.S.: I'm really sorry if your head hurts now :confused:

**Comment by aunetx** [comment]
Thanks, I will try to isolate the extension that cause problem (if it is the cause) and change the behavior of mine accordingly

ps : And don't worry for my head! I love trying to resolve challenges like that, and thanks to your list I have all the informations in hands :)

**Comment by aunetx** [comment]
Does my last update fix this issue too btw?

**Comment by mystiquewolf** [comment]
I think it is not fixed maybe (based on the language switcher).
![2020-05-27_00-58](https://user-images.githubusercontent.com/16529989/82954620-cae31c80-9fb5-11ea-8d04-54624ddd29f1.png)

I generally think now that i like the all white text color as it is, with a little decrese in transparency so it's still readable. For me dark text color is more difficult to read but that's just personal. Dark might seem nice to people. (It seemed nice to me at the beginning, i'm not sure now).

**Comment by aunetx** [comment]
Oh that's weird...

Would you mind giving me the output of this manipulation:

`Alt+f2`, then type `lg` (to open the debugger)
In the console:

```js
Main.panel.get_child_at_index(0)
// then the same with index 1, 2, 3... until error message
```

The results should be some objects named something like "panelLeft", "panelCenter" etc
If you can give me which object (and moreover which name) is at which index, I may be able to understand more in details ^^

**Comment by mystiquewolf** [comment]
![iT5DrI8 - Imgur](https://user-images.githubusercontent.com/16529989/83000356-e6304500-a012-11ea-9dc9-74b0e246ebb5.png)

**Comment by aunetx** [comment]
Oh OK that's very weird...
And what about `Main.panel.get_child_at_index(2).get_children()`?
(and maybe: `Main.panel.get_child_at_index(2).get_children().forEach((child) => { child.get_child_at_index(0).set_style("color:black"); })`? Does it change the color, or show an error ?) 
It's exactly the same as in my case, so I don't even understand why my last commits remove the ERROR label...

Sorry for being long, and don't worry if you don't have much time! I can try to replicate this bug myself now, as the other one was fixed ^^

**Comment by mystiquewolf** [comment]
Well, after each try what i do is i uninstall the cloned extension from GitHub, then install the regular one. When you tell me to run something, i remove it and again clone from the repo, so if you have pushed something then it's here.

Today what i noticed is that after i installed the cloned extension AND restarted the gnome-shell, the colors for the language were black. See below:
![2020-05-28_13-29](https://user-images.githubusercontent.com/16529989/83131584-b81d3480-a0e8-11ea-85c6-8901dd55e8ff.png)
However, when i opened the Nautilus files, the color of the language did not change, unlike the other colors. See below:
![2020-05-28_13-32](https://user-images.githubusercontent.com/16529989/83131639-d3883f80-a0e8-11ea-9ac6-983039a9c4f0.png)
These are the children of the object at index 2:
![EwlvcYW - Imgur](https://user-images.githubusercontent.com/16529989/83132031-78a31800-a0e9-11ea-90ea-540ed1adaf97.png)
They have a lot of functions and properties inside, i didn't take screenshots of them.

I also got the notification for the update, so i will uninstall the cloned extension and install from extensions to see how it goes.

**Comment by mystiquewolf** [comment]
I installed the extension via gnome site.

Before restart after change of colors:
![before_restart](https://user-images.githubusercontent.com/16529989/83134832-996d6c80-a0ed-11ea-9474-d9ee1d30ce3c.png)
After restart:
![after_restart](https://user-images.githubusercontent.com/16529989/83134874-a8541f00-a0ed-11ea-8be7-e23a8b777e11.png)
After reset to default settings:
![after_reset_to_default](https://user-images.githubusercontent.com/16529989/83134914-b9049500-a0ed-11ea-9b61-a6399f96cba4.png)
After reset to default settings 2nd image:
![after_reset_to_default_2](https://user-images.githubusercontent.com/16529989/83134945-c457c080-a0ed-11ea-86a9-350923c4f3fe.png)

**Comment by mystiquewolf** [comment]
After install it showed error, but some time after that it stopped showing the error after refreshing. Don't know whether some change like resetting settings or some color fixed it or it was something else.

**Comment by aunetx** [comment]
It seems really too hard to be fixed soon actually :(
I changed something else that may be fixing some things, but I still don't understand some parts of this bug... feel free to test it if you want to but I don't think it resolves this whole bug

I will push the extension to extensions.gnome.org so the ERROR bug is resolved, and we will see in some days if something has changed!

**Comment by aunetx** [comment]
You can now update the extension and see if the bug is removed :)
Probably not but everything is possible

**Comment by mystiquewolf** [comment]
I have one good and one bad news for you.

1. The extension works correctly when OpenWeather is disabled, even after gnome shell restart and/or before it.
2. It breaks when OpenWeather extension is enabled.

**Comment by aunetx** [comment]
Thanks a lot!
I fixed this bug, I don't know why OpenWeather caused this (adding a dummy child to the panel?) but that is good now :)

Reopen the issue if the bug still persists after an update via git, and I'm pushing this extension to extensions.gnome.org right now
