### ISSUE TITLE
Top bar is transparent when window touches it, which goes against selected setting

### ISSUE THREAD

**Issue by mystiquewolf** [aunetx/smart-transparent-top-bar#6]
This happens since about a week or so, just found the time to report it.

![2020-07-03_18-18](https://user-images.githubusercontent.com/16529989/86482045-d4506900-bd59-11ea-92b9-234a17c97408.png)

**Comment by aunetx** [comment]
Thanks for reporting, what is the transition distance settings that you are using?

I've never experienced this before

**Comment by mystiquewolf** [comment]
duration is 0.40, and distance is set to 5. Transparency/opacity/alpha of background when no window touches is 25.

**Comment by mystiquewolf** [comment]
Forgot to say that there is a red ERROR in gnome site.

**Comment by aunetx** [comment]
Hmm well I will try to fix this

The error is problematic too, did you restart the shell since the last extension's update? I guess so, but my own shell shows an error each time an extension is updated without shell restart

**Comment by mystiquewolf** [comment]
I have restarted the PC i believe some times. It works now, but it stops working from time to time.

**Comment by mystiquewolf** [comment]
Still an issue. Don't know what is happening. Log file [attached](https://1drv.ms/t/s!AsHYT07mKS7NgsAcF8B33oKUz-3Mow?e=xGyhtx).

**Comment by aunetx** [comment]
I'm sorry for the delay, I don't really have time to maintain the extension right now... But during next holidays I will try to!

And sorry for not being responsive :/

**Comment by mystiquewolf** [comment]
It's okay. Lately I'm also trying to limit the things that i do to a smaller set and stick to some kind of priorities. :)
That said, I've switched to KDE Plasma, so i'm not sure that i'll be able to help you anymore.

And thanks for commenting at the right time, yesterday i thrashed the log from OneDrive, but today i restored it. Sometimes God helps us.

**Comment by aunetx** [comment]
I'm sorry, I can't reproduce this issue... I will let it open some days more, and close it if nobody experience the same is that okay?

**Comment by mystiquewolf** [comment]
Yes, you are free to close it.

**Comment by aunetx** [comment]
Thanks! But I'm sorry for this issue, the problem is that I don't really use my own extension anymore... So it's hard for me to test it everyday
